language: node_js
node_js:
  - "8"
install:
  - npm install
cache:
  directories:
    - node_modules
script:
  - echo $(curl -s https://api.ipify.org)
  - gulp build
after_success:
  gulp deploy
deploy:
  provider: script
  skip_cleanup: true
  script: sshpass -p $SSH_PASS rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR ${SSH_USER}@${SSH_HOST}:${SSH_PATH}
  on:
    branch: master
