language: node_js
node_js:
  - "10"
install:
  - yarn install
cache:
  directories:
    - node_modules
script:
  - echo $(curl -s https://api.ipify.org)
  - gulp build
#after_success:
#  gulp deploy
#before_script:
#  - sudo apt-get install -qq sshpass
deploy:
  provider: script
  skip_cleanup: true
  script: gulp deploy
#  script: sshpass -p $SSH_PASS rsync -r --delete-after $TRAVIS_BUILD_DIR ${SSH_USER}@${SSH_HOST}:${SSH_PATH}
  on:
    branch: master
